site_name: Revos Documentation
site_description: A Python library for Revos API authentication and LangChain-based LLM tools
site_author: Revos Team
site_url: https://kavodsky.github.io/revos

repo_name: kavodsky/revos
repo_url: https://github.com/kavodsky/revos
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [revos]
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_root_toc_entry: false
            show_object_full_path: false
            show_category_heading: true
            show_if_no_docstring: false
            show_signature_annotations: true
            separate_signature: true
            line_length: 80
            merge_init_into_class: true
            show_bases: true
            show_submodules: true
            filters: ["!^_"]
            members_order: source
            docstring_options:
              ignore_init_summary: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quick-start.md
    - Configuration: getting-started/configuration.md
  - User Guide:
    - Authentication: user-guide/authentication.md
    - LLM Integration: user-guide/llm-integration.md
    - Token Management: user-guide/token-management.md
    - Multiple Models: user-guide/multiple-models.md
  - FastAPI Integration:
    - Basic Setup: fastapi/basic-setup.md
    - RUMBA_ Prefix Example: fastapi/rumba-example.md
    - Advanced Patterns: fastapi/advanced-patterns.md
    - Error Handling: fastapi/error-handling.md
    - Complete Example: fastapi/complete-example.md
  - Examples:
    - Basic Usage: examples/basic-usage.md
    - Configuration Examples: examples/configuration-examples.md
    - Custom Prefixes: examples/custom-prefixes.md
    - Multiple Models: examples/multiple-models.md
  - API Reference:
    - Configuration: api/configuration.md
    - Authentication: api/authentication.md
    - LLM Tools: api/llm-tools.md
    - Token Management: api/token-management.md
    - Exceptions: api/exceptions.md
  - Development:
    - Contributing: development/contributing.md
    - Testing: development/testing.md
    - Building: development/building.md
  - Changelog: changelog.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yourusername/revos
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/revos/
  version:
    provider: mike
